export const GET_PEOPLES_REQUEST = 'GET_PEOPLES_REQUEST'
export const GET_PEOPLES_SUCCESS = 'GET_PEOPLES_SUCCESS'
export const GET_PEOPLES_FAILURE = 'GET_PEOPLES_FAILURE'

export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST'
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS'
export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE'

export const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST'
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS'
export const GET_FILMS_FAILURE = 'GET_FILMS_FAILURE'

export const GET_FILM_REQUEST = 'GET_FILM_REQUEST'
export const GET_FILM_SUCCESS = 'GET_FILM_SUCCESS'
export const GET_FILM_FAILURE = 'GET_FILM_FAILURE'

export const GET_PLANETS_REQUEST = 'GET_PLANETS_REQUEST'
export const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS'
export const GET_PLANETS_FAILURE = 'GET_PLANETS_FAILURE'

export const GET_PLANET_REQUEST = 'GET_PLANET_REQUEST'
export const GET_PLANET_SUCCESS = 'GET_PLANET_SUCCESS'
export const GET_PLANET_FAILURE = 'GET_PLANET_FAILURE'

export const GET_SPECIES_REQUEST = 'GET_SPECIES_REQUEST'
export const GET_SPECIES_SUCCESS = 'GET_SPECIES_SUCCESS'
export const GET_SPECIES_FAILURE = 'GET_SPECIES_FAILURE'

export const GET_SPECIE_REQUEST = 'GET_SPECIE_REQUEST'
export const GET_SPECIE_SUCCESS = 'GET_SPECIE_SUCCESS'
export const GET_SPECIE_FAILURE = 'GET_SPECIE_FAILURE'

export const GET_STARSHIPS_REQUEST = 'GET_STARSHIPS_REQUEST'
export const GET_STARSHIPS_SUCCESS = 'GET_STARSHIPS_SUCCESS'
export const GET_STARSHIPS_FAILURE = 'GET_STARSHIPS_FAILURE'

export const GET_STARSHIP_REQUEST = 'GET_STARSHIP_REQUEST'
export const GET_STARSHIP_SUCCESS = 'GET_STARSHIP_SUCCESS'
export const GET_STARSHIP_FAILURE = 'GET_STARSHIP_FAILURE'

export const GET_VEHICLES_REQUEST = 'GET_VEHICLES_REQUEST'
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS'
export const GET_VEHICLES_FAILURE = 'GET_VEHICLES_FAILURE'

export const GET_VEHICLE_REQUEST = 'GET_VEHICLE_REQUEST'
export const GET_VEHICLE_SUCCESS = 'GET_VEHICLE_SUCCESS'
export const GET_VEHICLE_FAILURE = 'GET_VEHICLE_FAILURE'
